"""
Demo-only ML scorer for no-show risk.

Trained on the public Kaggle Medical No-Show dataset
(https://www.kaggle.com/datasets/joniarroba/noshowappointments).

NOT wired into live appointment creation — the operational schema intentionally
omits the demographic features (age, chronic conditions, SMS_received) that the
Kaggle model requires. This endpoint exists as a portfolio demo: given a feature
dict matching the Kaggle columns, return a predicted no-show probability.

Run scripts/train_noshow.py first to produce models/noshow_rf.joblib.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# joblib / sklearn are optional at import time; the endpoint returns 503 if absent.
try:
    import joblib
    import numpy as np

    _JOBLIB_AVAILABLE = True
except ImportError:
    _JOBLIB_AVAILABLE = False

MODEL_PATH = Path(__file__).resolve().parents[2] / "models" / "noshow_rf.joblib"

FEATURE_COLUMNS = [
    "Age",
    "Gender",
    "Scholarship",
    "Hipertension",
    "Diabetes",
    "Alcoholism",
    "Handcap",
    "SMS_received",
    "wait_days",
]

_model: Any = None


def get_model() -> Any | None:
    """Lazily load the trained model. Returns None if not available."""
    global _model
    if not _JOBLIB_AVAILABLE:
        return None
    if _model is None:
        if not MODEL_PATH.exists():
            return None
        _model = joblib.load(MODEL_PATH)
    return _model


def predict(features: dict) -> float | None:
    """
    Return P(no-show) in [0, 1], or None if the model file is not present.

    features must contain keys matching FEATURE_COLUMNS. Gender is encoded
    as 1 (Female) / 0 (Male) to match training encoding.
    """
    model = get_model()
    if model is None:
        return None
    row = [features.get(col, 0) for col in FEATURE_COLUMNS]
    proba = model.predict_proba(np.array([row]))[0]
    # class order: [no_show=0, no_show=1] — return P(no-show)
    classes = list(model.classes_)
    no_show_idx = classes.index(1) if 1 in classes else -1
    return float(proba[no_show_idx]) if no_show_idx >= 0 else float(proba[1])


# ── Demo demographic profiles ────────────────────────────────────────────────
# The Kaggle model needs demographic features the operational schema
# deliberately does not store. Those features used to be generated by
# seed_synthetic.py into a sidecar JSON file keyed by patient_uuid, which broke
# in two ways at once: the seed mints fresh UUIDs on every run, orphaning every
# profile in the committed file, and on Fly the file lives on an ephemeral disk,
# so any deploy or machine restart reverts it to whatever was baked into the
# image. Deriving the profile from the UUID instead makes it stable for a given
# patient, correct for patients seeded after the file was written, and immune to
# both failure modes. There is nothing to keep in sync because there is no file.

_PROFILE_PREVALENCE = {
    # Marginal rates from the Kaggle no-show cohort, used only to make the demo
    # profiles look plausible. They carry no clinical meaning.
    "scholarship": 0.10,
    "hipertension": 0.19,
    "diabetes": 0.11,
    "alcoholism": 0.03,
    "handcap": 0.05,
}


def demo_profile(patient_uuid: str) -> dict:
    """Deterministic synthetic demographics for one patient UUID.

    Same UUID always yields the same profile, on any machine, with no stored
    state. Synthetic demo data only -- never derived from, and never describing,
    a real person.
    """
    import hashlib
    import random as _random

    digest = hashlib.sha256(str(patient_uuid).encode()).digest()
    rng = _random.Random(int.from_bytes(digest[:8], "big"))
    return {
        "age": rng.randint(18, 85),
        "gender": rng.choice([0, 1]),
        "scholarship": int(rng.random() < _PROFILE_PREVALENCE["scholarship"]),
        "hipertension": int(rng.random() < _PROFILE_PREVALENCE["hipertension"]),
        "diabetes": int(rng.random() < _PROFILE_PREVALENCE["diabetes"]),
        "alcoholism": int(rng.random() < _PROFILE_PREVALENCE["alcoholism"]),
        "handcap": rng.randint(0, 2) if rng.random() < _PROFILE_PREVALENCE["handcap"] else 0,
        "_note": "Synthetic demo data only - derived from the UUID, not real PII",
    }
